---
ansible_python_interpreter: /usr/bin/env python3
ansible_user: root

boot_part: "{{ install_drive }}p1"
root_part: "{{ install_drive }}p2"

user:
  name: ashleigh
  fullname: Ashleigh Wilson
  uid: 1000
  gid: 1000
  groups: wheel,data,dialout
  shell: /bin/zsh
  files:
    - { from: .ssh/config, to: .ssh/ }
    - { from: .ssh/id_rsa.pub, to: .ssh/ }
    - { from: .ssh/personal.keyx, to: .ssh/ }
    - { from: Nextcloud/Apps/KeePassXC/Personal.kdbx, to: Nextcloud/Apps/KeePassXC/ }

system:
  groups:
    - { group: "data", gid: 1002 }

timezone: Europe/London

firewall:
  server:
    interfaces: br0, enp2s0
    ports:
    services:
      - dhcpv6-client
      - mdns
      - plex
      - samba-client
      - ssh

packages:
  fedora:
    core:
      - zsh
      - git
      - yadm
      - htop
      - ripgrep
      - fd-find
      - wget
      - neovim
      - python3-pip
      - gcc
      - g++
      - lazygit
      - ansible
      - copr-cli
      - fedpkg
      - sqlite
      - lua-language-server
      - nodejs-bash-language-server
      - mc
    desktop:
      - alacritty
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - file-roller
      - file-roller-nautilus
      - tela-icon-theme # from personal COPR repo
      - nerd-fonts # from personal COPR repo
      - adw-gtk3
      - gnome-tweaks
      - gnome-extensions-app
    flatpaks:
      - com.nextcloud.desktopclient.nextcloud
      - org.keepassxc.KeePassXC
    gnome_extensions:
      - blur-my-shell@aunetx
      - caffeine@patapon.info
      - hibernate-status@dromi
      - appindicatorsupport@rgcjonas.gmail.com
    pip:
      user:
        - gnome-extensions-cli
        - pynvim
    yarn:
      global:
        yaml-language-server # TODO: Add to install script
  arch:
    core:
      - zsh
      - git
      - yadm
      - htop
      - lazygit
      - ripgrep
      - wget
      - npm
      - gcc
      - neovim
      - steam
      - keepassxc
      - firefox
      - gnome-browser-connector
      - nextcloud-client
      - python-pip
      - adw-gtk3-git
      - tela-icon-theme-git
      - vmware-workstation
      - nfs-utils
      - linux-headers
      - gthumb
      - ffmpegthumbs
      - ncdu
      - gst-libav # H264 codec
      - fd # optional dependency for neovim
      - lua-language-server
      - yaml-language-server
      - bash-language-server
      - pyright
      - gnome-tweaks
      - gparted
      - ansible
      - phinger-cursors
      - nerd-fonts-complete
      - qt5-wayland
      - sshpass
      - bluez

services:
  - bluetooth.service

settings:
  gnome:
    # wallpaper
    - { key: "/org/gnome/desktop/background/picture-uri", value: "'file:///home/ashleigh/.local/share/backgrounds/2022-06-10-19-33-29-fox-forest.jpg'" }
   
    # window titlebar buttons
    - { key: "/org/gnome/desktop/wm/preferences/button-layout", value: "'appmenu:minimize,close'"}

    # disable automatic screen brightness
    - { key: "/org/gnome/settings-daemon/plugins/power/ambient-enabled", value: "false"}

    # enable gnome extensions
    - { key: "/org/gnome/shell/enabled-extensions", value: "[
          'caffeine@patapon.info',
          'blur-my-shell@aunetx',
          'hibernate-status@dromi',
          'appindicatorsupport@rgcjonas.gmail.com'
        ]"}

    # configure favourite apps on the dock
    - { key: "/org/gnome/shell/favorite-apps", value: "[
          'org.gnome.Nautilus.desktop',
          'org.gnome.Terminal.desktop',
          'firefox.desktop',
          'thunderbird.desktop',
          'org.keepassxc.KeePassXC.desktop',
          'org.gnome.Calendar.desktop'
        ]"}
    
    # dock transparency
    - { key: "/org/gnome/shell/extensions/dash-to-dock/background-opacity", value: "0.0"}

    # max icon size
    - { key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size", value: "48"}
    
    # isolate workspaces
    - { key: "/org/gnome/shell/extensions/dash-to-dock/isolate-workspaces", value: "true"}

    # app running indicator
    - { key: "/org/gnome/shell/extensions/dash-to-dock/running-indicator-style", value: "'DOTS'"}
    
    # show favourite apps on dock
    - { key: "/org/gnome/shell/extensions/dash-to-dock/show-favorites", value: "true"}
    
    # hide the show apps button on dock
    - { key: "/org/gnome/shell/extensions/dash-to-dock/show-show-apps-button", value: "false"}
    
    # dock transparency mode
    - { key: "/org/gnome/shell/extensions/dash-to-dock/transparency-mode", value: "'FIXED'"}
    
    - { key: "/org/gnome/shell/extensions/dash-to-dock/click-action", value: "'previews'"}
    - { key: "/org/gnome/shell/extensions/dash-to-dock/dock-position", value: "'BOTTOM'"}
    - { key: "/org/gnome/shell/extensions/dash-to-dock/height-fraction", value: "0.9"}
    - { key: "/org/gnome/shell/extensions/dash-to-dock/scroll-action", value: "'cycle-windows'"}
    - { key: "/org/gnome/shell/extensions/dash-to-dock/show-mounts", value: "false"}
    - { key: "/org/gnome/shell/extensions/dash-to-dock/show-mounts-only-mounted", value: "false"}

    # gtk theme
    - { key: "/org/gnome/desktop/interface/gtk-theme", value: "'adw-gtk3'"}
    
    # icon theme
    - { key: "/org/gnome/desktop/interface/icon-theme", value: "'Tela-purple'"}
    
    # keyboard layout
    - { key: "/org/gnome/desktop/input-sources/sources", value: "[('xkb', 'gb')]"}

    # touchpad
    - { key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled" , value: "true"}
    
    # window manager
    - { key: "/org/gnome/mutter/edge-tiling", value: "true"}

    # gnome tweaks
    - { key: "/org/gnome/tweaks/show-extensions-notice" , value: "false" }
    
    # nautilus
    - { key: "/org/gnome/nautilus/preferences/default-folder-viewer" , value: "'icon-view'"}
    - { key: "/org/gnome/nautilus/preferences/recursive-search" , value: "'always'"}
    - { key: "/org/gnome/nautilus/preferences/search-view" , value: "'list-view'"}
    - { key: "/org/gnome/nautilus/preferences/show-directory-item-counts" , value: "'always'"}
    - { key: "/org/gnome/nautilus/preferences/show-image-thumbnails" , value: "'always'"}

    # key bindings
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding" , value: "'<Super>Return'"}
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command" , value: "'gnome-terminal'"}
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name" , value: "'Terminal'"}
    - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings", value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']" }

    # terminal settings
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color", value: "'rgb(40,44,52)'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent", value: "6" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/cursor-background-color", value: "'rgb(187,194,207)'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/cursor-colors-set", value: "true" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/cursor-foreground-color", value: "'rgb(40,44,52)'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/cursor-shape", value: "'block'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font", value: "'JetBrainsMono Nerd Font {{ font_size }}'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color", value: "'rgb(187,194,207)'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/palette", value: "['rgb(40,44,52)', 'rgb(255,108,107)', 'rgb(152,190,101)', 'rgb(236,190,123)', 'rgb(81,175,239)', 'rgb(169,161,225)', 'rgb(70,217,255)', 'rgb(187,194,207)', 'rgb(63,68,74)', 'rgb(255,108,107)', 'rgb(152,190,101)', 'rgb(218,133,72)', 'rgb(81,175,239)', 'rgb(169,161,225)', 'rgb(70,217,255)', 'rgb(239,239,239)']" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollbar-policy", value: "'never'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/title-mode", value: "'replace'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font", value: "false" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors", value: "false" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-transparent-background", value: "true" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/visible-name", value: "'DoomOne'" }

    # blur my shell extension
    - { key: "/org/gnome/shell/extensions/blur-my-shell/dash-to-dock/blur", value: "false" }
    - { key: "/org/gnome/shell/extensions/blur-my-shell/panel/blur" , value: "true"}

    # caffeine extension
    - { key: "/org/gnome/shell/extensions/caffeine/user-enabled", value: "true"}

