---
ansible_python_interpreter: /usr/bin/env python3
ansible_user: root

boot_part: "{{ install_drive }}p1"
root_part: "{{ install_drive }}p2"

user:
  name: ashleigh
  fullname: Ashleigh Wilson
  uid: 1000
  gid: 1000
  groups: wheel,data
  shell: /bin/zsh
  files:
    - { from: .ssh/config, to: .ssh/ }
    - { from: .ssh/id_rsa.pub, to: .ssh/ }
    - { from: .ssh/personal.keyx, to: .ssh/ }
    - { from: Nextcloud/Apps/KeePassXC/Personal.kdbx, to: Nextcloud/Apps/KeePassXC/ }

system:
  groups:
    - { group: "data", gid: 1002 }

timezone: Europe/London

packages:
  arch:
    core:
      - zsh
      - git
      - yadm
      - htop
      - lazygit
      - ripgrep
      - wget
      - npm
      - gcc
      - neovim
      - steam
      - keepassxc
      - firefox
      - gnome-browser-connector
      - nextcloud-client
      - python-pip
      - adw-gtk3-git
      - tela-icon-theme-git
      - vmware-workstation
      - nfs-utils
      - linux-headers
      - gthumb
      - ffmpegthumbs
      - ncdu
      - gst-libav # H264 codec
      - fd # optional dependency for neovim
      - lua-language-server
      - yaml-language-server
      - bash-language-server
      - pyright
      - gnome-tweaks
      - gparted
      - ansible
      - phinger-cursors
      - nerd-fonts-complete
      - qt5-wayland
      - sshpass
      - bluez

services:
  - bluetooth.service

settings:
  gnome:
    # wallpaper
    - { key: "/org/gnome/desktop/background/picture-uri", value: "'file:///home/ashleigh/.local/share/backgrounds/2022-06-10-19-33-29-fox-forest.jpg'" }
   
    # window titlebar buttons
    - { key: "/org/gnome/desktop/wm/preferences/button-layout", value: "'appmenu:minimize,close'"}

    # disable automatic screen brightness
    - { key: "/org/gnome/settings-daemon/plugins/power/ambient-enabled", value: "false"}

    # enable gnome extensions
    - { key: "/org/gnome/shell/enabled-extensions", value: "[
          'caffeine@patapon.info',
          'blur-my-shell@aunetx',
          'hibernate-status@dromi',
          'trayIconsReloaded@selfmade.pl',
          'dash-to-dock@micxgx.gmail.com'
        ]"}

    # configure favourite apps on the dock
    - { key: "/org/gnome/shell/favorite-apps", value: "[
          'org.gnome.Nautilus.desktop',
          'Alacritty.desktop',
          'firefox.desktop',
          'thunderbird.desktop',
          'org.keepassxc.KeePassXC.desktop',
          'org.gnome.Calendar.desktop'
        ]"}
    
    # dock transparency
    - { key: "/org/gnome/shell/extensions/dash-to-dock/background-opacity", value: "0.0"}

    # max icon size
    - { key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size", value: "48"}
    
    # isolate workspaces
    - { key: "/org/gnome/shell/extensions/dash-to-dock/isolate-workspaces", value: "true"}

    # app running indicator
    - { key: "/org/gnome/shell/extensions/dash-to-dock/running-indicator-style", value: "'DOTS'"}
    
    # show favourite apps on dock
    - { key: "/org/gnome/shell/extensions/dash-to-dock/show-favorites", value: "true"}
    
    # hide the show apps button on dock
    - { key: "/org/gnome/shell/extensions/dash-to-dock/show-show-apps-button", value: "false"}
    
    # dock transparency mode
    - { key: "/org/gnome/shell/extensions/dash-to-dock/transparency-mode", value: "'FIXED'"}
    
    # gtk theme
    - { key: "/org/gnome/desktop/interface/gtk-theme", value: "'adw-gtk3'"}
    
    # icon theme
    - { key: "/org/gnome/desktop/interface/icon-theme", value: "'Tela-purple'"}
    

    # - { key: , value: }
