---
ansible_python_interpreter: /usr/bin/env python3
ansible_user: root

boot_part: "{{ install_drive }}1"
root_part: "{{ install_drive }}2"

user:
  name: ashleigh
  fullname: Ashleigh Wilson
  password: $6$BHk8btTk/MWBZrq4$XPz1EEw2n/Yi4kvXovgjHkSY9Fx3apH3MrDFhHutWZgMi7GsO6jmEIqOH.zbeh6kug/dSxLRqmr36qxkwdgF8/
  uid: 1000
  gid: 1000
  groups: wheel
  shell: /bin/zsh

timezone: Europe/London

btrfs:
  enabled: true
  subvolumes:
    - subvolume: "@snapshots"
      path: "/.snapshosts"
    - subvolume: "@home"
      path: "/home"
    - subvolume: "@log"
      path: "/var/log"
    - subvolume: "@cache"
      path: "/var/cache"
    # - subvolume: "@tmp"
    #   path: "/var/tmp"
    # - subvolume: "@data"
    #   path: "data"
    #   disable_cow: true

packages:
  # Essential packages for a base arch install.
  base:
    - base
    - base-devel
    - linux-firmware
    - efibootmgr
    - grub
    - grub-btrfs
    - sudo
    - networkmanager
    - neovim
    - openssh
    - btrfs-progs
    - zsh
    - git
    - python

  # Core packages which are common across all installs.
  core:
    - neovim
    - zsh
    - git
    - yadm
    - htop
    - lazygit
    - ripgrep
    - wget
    - npm
    - gcc
    - g++
    - cronie

  # Core npm packages which are common across all installs.
  core_npm:
    - pyright
    - bash-language-server
    - yaml-language-server
    # TODO: - lua-language-server
