---
all:
  children:
    servers:
      hosts:
        server.lan:
          ansible_host: 192.168.1.2
          ansible_python_interpreter: /usr/bin/env python
    desktops:
      hosts:
        xps.lan:
        fractal.lan:
      vars:
        dns_server: 192.168.1.85
    vms:
      hosts:
        test.vm:
          ansible_host: 192.168.1.208
          ansible_user: root
          ansible_ssh_pass: pass
          ansible_python_interpreter: /usr/bin/env python
          ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
    vars:
