---
- hosts: all
  roles:
    - prechecks
    - core
 #   - users
 #   - dotfiles
 #   - firewalld
 #   - storage

#- hosts: servervm,server
#  roles:
#    - nfs-server
#    - docker
    # - virtualization

- hosts: fractal,xps
  roles:
    - nfs-client
#    - gnome
#    - desktop

# Install snapper and create initial snapshots of fresh install
#- hosts: all
#  roles:
#    - snapper

# TODO:
# nerd-fonts-roboto-mono
# phinger-cursors
# tela-icon-theme
# qt5-wayland
#

