---
- hosts: all
  roles:
    - prechecks
    - core
    - users
 #   - dotfiles
 #   - firewalld
 #   - storage

#- hosts: servervm,server
#  roles:
#    - nfs-server
#    - docker
    # - virtualization

- hosts: fractal,xps
  roles:
    - nfs-client
    - gnome
#    - desktop

# Install snapper and create initial snapshots of fresh install
#- hosts: all
#  roles:
#    - snapper

# TODO:
# configure nautilus settings
# Add key bindings to open terminal
# sudo systemctl enable --now vmware-networks.service vmware-usbarbitrator.service

