---
- name: Install psutil pip package for dconf configuration
  pip:
    name: psutil

- name: Update gnome settings
  become: yes
  become_user: "{{ user.name }}"
  loop: "{{ settings.gnome }}" 
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
    state: present
