---
- name: Install psutil pip package for dconf configuration
  pip:
    name: psutil

- name: Update gnome settings
  loop: "{{ settings.gnome }}" 
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
