---
- name: Create and configure users
  block:

    - name: Delete default /etc/skel files
      file: path=/etc/skel state=absent

    - name: Create user group
      group:
        name: "{{ user.name }}"
        state: present
        gid: "{{ user.gid }}"

    - name: Create normal user
      user:
        name: "{{ user.name }}"
        comment: "{{ user.fullname }}"
        uid: "{{ user.uid }}"
        group: "{{ user.name }}"
        groups: "{{ user.groups }}"
        append: yes
        shell: /bin/zsh
        password: "{{ user.password }}"

    - name: Create authorized keys
      authorized_key:
        user: "{{ user.name }}"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
