---
- name: Create and configure users
  block:

    - name: Delete default /etc/skel files
      file: path=/etc/skel state=absent

    - name: Create user groups
      group:
        name: "{{ user.name }}"
        state: present
        gid: "{{ user.gid }}"

    - name: Create users
      user:
        name: "{{ user.name }}"
        comment: "{{ user.fullname }}"
        uid: "{{ user.uid }}"
        group: "{{ user.name }}"
        groups: "{{ user.groups }}"
        append: yes
        shell: /bin/zsh
        password: "{{ user.password }}"

    - name: Create authorized keys
      authorized_key:
        user: ashleigh
        state: present
        key: "{{ lookup('file', '/home/{{ user.name }}/.ssh/id_rsa.pub') }}"
