---
- name: Create NFS mount directory
  become: yes
  file:
    path: /media/Data
    state: directory
    mode: '0755'

- name: Setup and enable NFS client
  become: yes
  mount:
    src: 192.168.1.2:/mnt/data
    path: /media/Data
    opts: noauto,user,_netdev,bg
    state: present
    fstype: nfs
    boot: no

