---
- name: Setup and enable NFS server
  block:
    - name: Install NFS server
      package:
        name:
          - nfs-utils
    # - name: Configure /etc/exports
    # - name: Make NFS share directories
    - name: Start nfs-server.service
      systemd:
        name: nfs-server.service
        state: started
        enabled: true
    # - name: Enable nfs-server and maybe rpc-bind?
    # - name: firewall allow nfs3/nfs4/nfs/mountd/rpc-bind

